### ISSUE TITLE
Réparer la preview Netlify pour la PR profil SIRI 1.7

### ISSUE THREAD

**Issue by thbar** [etalab/transport-normes-site#14]
J'ai mis un peu de temps à retrouver le "bon" projet Netlify où ça se passe (vu le délai), le voici:
- https://app.netlify.com/teams/transport-data-gouv-fr/overview

J'ajouterai ça au README si ça n'est pas déjà le cas.

**Comment by thbar** [comment]
J'ai réparé et c'est déployé ici:
- https://deploy-preview-13--transport-normes.netlify.app/normes/siri/profil-france/

**Comment by thbar** [comment]
Non visible publiquement ! Merci @Aurige - on va corriger.

**Comment by prhod** [comment]
Discuté en GT7 : Le lien https://deploy-preview-13--transport-normes.netlify.app/normes/siri/profil-france/ fonctionne bien, c'est https://app.netlify.com/teams/transport-data-gouv-fr/overview qui n'est pas publique.
=> normal

**Comment by thbar** [comment]
La preview est bien réparée, et lisible en public de façon vérifiée !
